### PR TITLE
Enable pushing to phabriactor using moz-phab

### PR DESCRIPTION
**Pull request by jgraham**
Now that inbound is gone, we have to push to autoland. But pushing to
autoland is hard because we struggle to find a time when it's open and
we don't hit a conflict with lando. Instead what we'd like is to end
up in the lando queue, but so far lando only knows how to read from
phabricator. So as a temporary solution we adopt the following
process:

* Push the landing to Phabricator using moz-phab
* Needinfo the wpt sync user to manually push the commits to lando and
  invoke lando (ignoring all the warnings about unlanded code).

### CODE REVIEW

**Comment by jgraham** [comment]
Note that this depends on dependencies of https://bugzilla.mozilla.org/show_bug.cgi?id=1596130

**Comment by dhdavvie** [comment]
Do we want to rebase this and merge it to master?

**Comment by jgraham** [comment]
I think we would need a way to pref it off

**Comment by jgraham** [comment]
I don't think there's a need to do this at the moment.

**Pull request closed without merging**
