### PR TITLE
Convert type comments to type annotations

### PR DESCRIPTION
**Pull request by KushalBeniwal**
I started working on issue #797.
If you have any suggestions please do comment and I'll work on them.

### CODE REVIEW

**Comment by KushalBeniwal** [comment]
Can someone guide me on why the tests are failing.

**Comment by denschub** [comment]
Hey there, @KushalBeniwal! Sorry for the delay here.

Are you still interested in working on this?

**Comment by KushalBeniwal** [comment]
Yes @denschub, I'm still interested in working on this.
Can you please guide me on why the test cases are failing as there weren't any errors that I'm aware of.

**Comment by denschub** [comment]
Unfortunately, I can't easily tell you that, because this PR is closed and thus the tests are hidden. Since I also cannot reopen, it looks like you may have deleted your fork or your branch.

By the way, there is no need to do the type annotation changes by hand! There is a tool, https://github.com/ilevkivskyi/com2ann, that should do this automatically. So what I suggest is that you run that tool on our code to automatically change all the type annotations, and then open a new PR so we can look at eventual failures together.

**Comment by KushalBeniwal** [comment]
> Since I also cannot reopen, it looks like you may have deleted your fork or your branch.

Sorry about that, I deleted the fork when I closed the PR.

> There is a tool, https://github.com/ilevkivskyi/com2ann, that should do this automatically. 

Thanks for the help, I'll open a new PR.

**Pull request closed without merging**
