### PR TITLE
Automatically update metadata for bug changes

### PR DESCRIPTION
**Pull request by jgraham**
This is based on https://github.com/mozilla/wpt-sync/pull/586 so not suitable to merge yet.

### CODE REVIEW

**Comment by jgraham** [comment]
This stuff probably needs tests, but I can't think of the best way to structure them without basically mocking everything. I verified it works manually and submitted https://github.com/jgraham/wpt-metadata/commit/0ed2a53c0f313203225335cf2100b468705d8d14

**Comment by dhdavvie** [comment]
Is this ready for review?

**Comment by jgraham** [comment]
> Is this ready for review?

Yes, although I think it wants more tests, feedback would be useful at this point.

**Comment by jgraham** [comment]
Writing automated tests for this was turning out to be rather tricky since one needs to generate a fake metadata repo and combine it with cached bugzilla queries. I suggest we merge it for now since the failure modes are not serious and defer writing a test.

**Pull request merged**
